<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Countries extends Model
{
    use HasFactory;

    protected $fillable =[
        'title','city_id','photo_country'
    ];
    public function services(){
        return $this->hasMany(Service::class,'countries_id');
    }
    public function cities(){
        return $this->belongsTo(City::class,'city_id');
    }
    public function application(){
        return $this->hasMany(Application::class,'city_respond_id');
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Countries::deleting(function ($countries) {
            $countries->cities()->delete();
            $countries->services()->delete();
        });
    }
}
