<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $fillable=[
        'countries_id','residence','feeding','excursion'
    ];
    public function countries(){
        return $this->belongsTo(Countries::class,'countries_id');
    }
    public function tours(){
        return $this->hasMany(Tour::class, 'service_id');
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        Service::deleting(function ($service) {
            $service->tours()->delete();

        });
    }
}
